---
dependency:
  name: {{ cookiecutter.dependency_name }}
driver:
  name: docker
lint:
  name: {{ cookiecutter.lint_name }}
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos7-{{ cookiecutter.role_name }}
    image: leandelivery/docker-systemd:centos7
    privileged: {{ cookiecutter.docker_privileged }}
    env:
      TERM: xterm
    groups:
      - rhel_family
  - name: test-docker-ubuntu1804-{{ cookiecutter.role_name }}
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: {{ cookiecutter.docker_privileged }}
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    env:
      TERM: xterm
    groups:
      - debian_family
provisioner:
  name: {{ cookiecutter.provisioner_name }}
  lint:
    name: {{ cookiecutter.provisioner_lint_name }}
scenario:
  name: default
verifier:
  name: {{ cookiecutter.verifier_name }}
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: {{ cookiecutter.verifier_lint_name }}
